# Самостоятельный проект 1


## Часть 1

### Задание 1.1

Создайте переменную и поместите в неё строку 'Привет! Это мой первый проект на Python!'.

In [2]:
#прекод
hello = "Привет! Это мой первый проект на Python!"
hello

'Привет! Это мой первый проект на Python!'


### Задание 1.2

Решите уравнение с помощью Python, предварительно упростив выражение на бумаге:

$2x = 2 - (8 + 4x).$

Выведите на экран результат решения — значение переменной $x.$

In [3]:
#прекод
x = -6/6
x

-1.0


### Задание 1.3

В переменной `pi` находится приблизительное значение числа $\pi{:}$ `3.1415926535`. 

1. Вычислите квадратный корень из полученного числа. 
2. Округлите результат до двух знаков после запятой. 
3. Выведите результат на экран.

In [4]:
#прекод
pi = '3.1415926535'
sqrt = float(pi) ** 0.5

sqrt = round(sqrt, 2)
sqrt

1.77


### Задание 1.4

Напишите функцию, которая будет переворачивать целые числа, то есть записывать их цифры в обратном порядке. Например, число 734 превратится в 437. Покажите работу функции на примере.

In [5]:
#прекод
def reverse_int(x):
    
    negative_digit = x < 0
    if negative_digit:
        x = -x
        
    y = x % 10
    x2 = y
    x = x // 10
    
    while x > 0:
        y = x % 10
        x = x // 10
        x2 = x2 * 10
        x2 = x2 + y
        
    return x2

reverse_int(-123456789)

987654321


### Задание 1.5

Подсчитайте количество символов в строке `'Функцию pow стоит применять только с третьим аргументом (остаток по модулю), тогда её использование может быть оправдано.'` Результат выведите на экран.

In [6]:
#прекод
my_str_2 = 'Функцию pow имеет смысл применять только с третьим аргументом (остаток по модулю), тогда её использование может быть оправдано.'

total_str = 0
for i in my_str_2:
    total_str += 1
    
total_str
len(my_str_2)

127


### Задание 1.6

Отобразите часть предыдущей строки, начиная с 63-го символа и до конца.

In [7]:
#прекод
my_str_2 = 'Функцию pow имеет смысл применять только с третьим аргументом (остаток по модулю), тогда её использование может быть оправдано.'

my_str_2[62:]

'(остаток по модулю), тогда её использование может быть оправдано.'


### Задание 1.7

В строке `'Если ск0р0сть важна, т0 для извлечения к0рня видим0 нужн0 исп0льз0вать специальн0 п0дг0т0вленную для эт0г0 функцию.'` допущена ошибка: многие буквы `'о'` заменены на `0`. Исправьте ошибку и выведите результат на экран.

In [8]:
#прекод
my_str_3 = 'Если ск0р0сть важна, т0 для извлечения к0рня видим0 нужн0 исп0льз0вать специальн0 п0дг0т0вленную для эт0г0 функцию.'
my_str_3.replace('0', 'о')

'Если скорость важна, то для извлечения корня видимо нужно использовать специально подготовленную для этого функцию.'


### Задание 1.8

Дан список из слов. Найдите три самых длинных слова и выведите их на экран.

In [9]:
#прекод
list_word = ['Зеркало', 'Синица', 'Горнодобывающий', 'Излюбленный', 'Карта', 'Миг', 'Свора', 'Травоядный', 'Монокль']

sorted_list = sorted(list_word, key=len, reverse=True)

longest_words = sorted_list[:3]

longest_words

['Горнодобывающий', 'Излюбленный', 'Травоядный']


### Задание 1.9

В переменной `my_list` лежит список списков. Внутренние списки состоят из чисел и строк, которые представляют собой целые числа. 

Поправьте типы:

- Измените тип на `int` у тех значений, которые представляют целые числа, но являются строками.
- Если элемент является числовым типом, то не меняйте его.

Отобразите изменённый список на экране.

In [10]:
import copy

#прекод
my_list = [['7', '2', 6 , 7.5, '7.5'],
            ['6', '7', 7, '8.1', '7.2'],
            ['6.5', '18', 1998, '6'],
            ['44', 5, '84', '21']]

for sublist in my_list:
    for i in range(len(sublist)):
        item = sublist[i]
        if isinstance(item, str):
            if item.isdigit() or (item[0] == '-' and item[1:].isdigit()):
                sublist[i] = int(item)
my_list

[[7, 2, 6, 7.5, '7.5'],
 [6, 7, 7, '8.1', '7.2'],
 ['6.5', 18, 1998, 6],
 [44, 5, 84, 21]]


### Задание 1.10

Создайте функцию, которая будет принимать на вход длины трёх отрезков, и определять, можно ли из таких отрезков составить треугольник. Напомним, что у треугольника сумма длин двух сторон должна быть больше длины третьей стороны. 

Длины отрезков должны быть целыми числами. По умолчанию длина одного отрезка должна равняться 10, с возможностью изменения. 

Проверьте функцию на своём примере.

In [11]:
#прекод
def triangle_calculation(a, b, c):
    
    if a + b > c and b + c > a and a + c > b:
        print("Треугольник существует")
    else:
        print("Треугольник не существует")

triangle_calculation(14, 15, 25)

Треугольник существует


### Задание 1.11

Составьте функцию, которая: 

- принимает на вход целое число,
- отображает на экране таблицу умножения на это число.

Если не вводить аргумент, то функция должна отобразить таблицу умножения на 1. 

При вводе дробного числа, функция должна отобразить сообщение `'Для дробных чисел я не считаю!'`

In [12]:
#прекод
def multiplication_table(digit = 1):
    if isinstance(digit, float):
            print('Для дробных чисел я не считаю!')
    elif digit >= 1:
        for i in range(1, 11):
            print(f"{digit} * {i} = {digit * i}")
        
multiplication_table(12.3)

Для дробных чисел я не считаю!

In [13]:
multiplication_table(4)

4 * 1 = 4
4 * 2 = 8
4 * 3 = 12
4 * 4 = 16
4 * 5 = 20
4 * 6 = 24
4 * 7 = 28
4 * 8 = 32
4 * 9 = 36
4 * 10 = 40


### Задание 1.12

Есть список строк с названиями и типами населённых пунктов. Переделайте список так, чтобы в нём остались только названия населённых пунктов. Например, если строка выглядит как `'посёлок городского типа Антополь'`, то в результате должно остаться только `'Антополь'`.

In [14]:
#прекод
locality_list = ['Санкт-Петербург', 'посёлок Шушары', 'городской посёлок Янино-1',
       'посёлок Парголово', 'посёлок Мурино', 'Ломоносов', 'Сертолово',
       'Петергоф', 'Пушкин', 'деревня Кудрово', 'Коммунар', 'Колпино',
       'поселок городского типа Красный Бор', 'Гатчина', 'поселок Мурино',
       'деревня Фёдоровское', 'Выборг', 'Кронштадт', 'Кировск',
       'деревня Новое Девяткино', 'посёлок Металлострой',
       'посёлок городского типа Лебяжье',
       'посёлок городского типа Сиверский', 'поселок Молодцово',
       'поселок городского типа Кузьмоловский',
       'садовое товарищество Новая Ропша', 'Павловск',
       'деревня Пикколово', 'Всеволожск', 'Волхов', 'Кингисепп',
       'Приозерск', 'Сестрорецк', 'деревня Куттузи', 'посёлок Аннино',
       'поселок городского типа Ефимовский', 'посёлок Плодовое',
       'деревня Заклинье', 'поселок Торковичи', 'поселок Первомайское',
       'Красное Село', 'посёлок Понтонный', 'Сясьстрой', 'деревня Старая',
       'деревня Лесколово', 'посёлок Новый Свет', 'Сланцы',
       'село Путилово', 'Ивангород', 'Мурино', 'Шлиссельбург',
       'Никольское', 'Зеленогорск', 'Сосновый Бор', 'поселок Новый Свет',
       'деревня Оржицы', 'деревня Кальтино', 'Кудрово',
       'поселок Романовка', 'посёлок Бугры', 'поселок Бугры',
       'поселок городского типа Рощино', 'Кириши', 'Луга', 'Волосово',
       'Отрадное', 'село Павлово', 'поселок Оредеж', 'село Копорье',
       'посёлок городского типа Красный Бор', 'посёлок Молодёжное',
       'Тихвин', 'посёлок Победа', 'деревня Нурма']

processed_list = []
for s in locality_list:
    found_capital = False
    for i, char in enumerate(s):
        if char.isupper():
            processed_list.append(s[i:])
            found_capital = True
            break
    if not found_capital:
        processed_list.append(s)
        
processed_list

['Санкт-Петербург',
 'Шушары',
 'Янино-1',
 'Парголово',
 'Мурино',
 'Ломоносов',
 'Сертолово',
 'Петергоф',
 'Пушкин',
 'Кудрово',
 'Коммунар',
 'Колпино',
 'Красный Бор',
 'Гатчина',
 'Мурино',
 'Фёдоровское',
 'Выборг',
 'Кронштадт',
 'Кировск',
 'Новое Девяткино',
 'Металлострой',
 'Лебяжье',
 'Сиверский',
 'Молодцово',
 'Кузьмоловский',
 'Новая Ропша',
 'Павловск',
 'Пикколово',
 'Всеволожск',
 'Волхов',
 'Кингисепп',
 'Приозерск',
 'Сестрорецк',
 'Куттузи',
 'Аннино',
 'Ефимовский',
 'Плодовое',
 'Заклинье',
 'Торковичи',
 'Первомайское',
 'Красное Село',
 'Понтонный',
 'Сясьстрой',
 'Старая',
 'Лесколово',
 'Новый Свет',
 'Сланцы',
 'Путилово',
 'Ивангород',
 'Мурино',
 'Шлиссельбург',
 'Никольское',
 'Зеленогорск',
 'Сосновый Бор',
 'Новый Свет',
 'Оржицы',
 'Кальтино',
 'Кудрово',
 'Романовка',
 'Бугры',
 'Бугры',
 'Рощино',
 'Кириши',
 'Луга',
 'Волосово',
 'Отрадное',
 'Павлово',
 'Оредеж',
 'Копорье',
 'Красный Бор',
 'Молодёжное',
 'Тихвин',
 'Победа',
 'Нурма']


## Часть 2

### Задание 2.1

Импортируйте библиотеку pandas. Составьте объект Series, в котором будут содержаться ингредиенты салата. Отобразите переменную на экране.

Ингредиенты: зелёный горошек, колбаса варёная, майонез, картофель отварной, огурцы маринованные, морковь отварная.

In [15]:
#прекод
import pandas as pd

df = pd.Series(['зелёный горошек', 'колбаса варёная', 'майонез', 'картофель отварной', 'огурцы маринованные', 'морковь отварная'])
df

0        зелёный горошек
1        колбаса варёная
2                майонез
3     картофель отварной
4    огурцы маринованные
5       морковь отварная
dtype: object


### Задание 2.2

Создайте Dataframe, состоящий из элементов:

- в первом столбце — имена капитанов команд;
- во втором столбце — названия команд;
- в третьем столбце — число очков, набранных командой.

Столбцы назовите: `name`, `command`, `score`. Данные вы найдёте в переменных. 

Обязательное условие: используйте словарь для создания Dataframe.

In [16]:
#прекод
name = ['Александр', 'Дмитрий', 'Анна', 'Виктория']
command = ['Серебряный диск', 'Медное копьё', 'Великий шар', 'Стремительный клинок']
score = [90, 40, 80, 98]

df_dict = {
    'name': name,
    'command': command,
    'scrore': score
}
df = pd.DataFrame(df_dict)
df

        name               command  scrore
0  Александр       Серебряный диск      90
1    Дмитрий          Медное копьё      40
2       Анна           Великий шар      80
3   Виктория  Стремительный клинок      98


### Задание 2.3

Выполните предыдущее задание, но с другим обязательным условием: используйте список списков для создания Dataframe.

In [17]:
#прекод
df_list = pd.DataFrame(list(zip(name, command, score)), columns = ['name', 'command', 'score'])
df_list

        name               command  score
0  Александр       Серебряный диск     90
1    Дмитрий          Медное копьё     40
2       Анна           Великий шар     80
3   Виктория  Стремительный клинок     98


### Задание 2.4

В рамках тестового задания вы поработаете с новым датасетом. В нём содержится информация о доставках товаров в различные районы города. Выгрузите в переменную `df_proj` файл `delivery_proj`. Датасет находится по адресу `/datasets/delivery_proj.csv`

Отобразите первые пять строк этого датасета.

In [18]:
#прекод
df_proj = pd.read_csv('/datasets/delivery_proj.csv')
df_proj.head()

,order_id,time_order,Time_delivery,last_name,first_name,gender,District,discont,var_product,price,quantity,deliveryman,transport
0,224,2023-01-22 10:31:30.000,2023-01-22 10:49:30.000,Журавлев,Денис,Мужской,Фонтанный квартал,2,Фондю,48.43,1,Анастасия Морозова,велосипед
1,2174,2023-01-30 15:20:17.000,2023-01-30 17:09:17.000,Ершова,Ольга,Женский,Радужная степь,0,Пад тай,19.10,3,Анастасия Морозова,велосипед
2,2076,2023-02-24 03:48:17.000,2023-02-24 04:42:17.000,Суханов,Артем,Мужской,Радужная степь,3,Кимчи,39.88,1,Павел Семенов,автомобиль
3,2337,2023-01-18 21:46:55.000,2023-01-18 23:02:55.000,Веселов,Валерий,Мужской,Радужная степь,0,Муссака,32.99,2,Иван Лебедев,автомобиль
4,1140,2023-02-02 17:20:33.000,2023-02-02 18:13:33.000,Калинина,Ирина,Женский,Эмпайровское кольцо,2,Тапас,29.16,2,Иван Лебедев,автомобиль


### Задание 2.5

Названия некоторых столбцов датасета написаны некорректно: некоторые названия начинаются с заглавной буквы, а в название `discont` есть опечатка. Переделайте датасет так, чтобы в названиях столбцов не было заглавных букв, а название столбца `discont` исправьте на `discount`. Отобразите первые пять строк нового датасета.

In [19]:
#прекод
df_proj.columns = df_proj.columns.str.lower().str.replace('discont', 'discount')
df_proj.head()

,order_id,time_order,time_delivery,last_name,first_name,gender,district,discount,var_product,price,quantity,deliveryman,transport
0,224,2023-01-22 10:31:30.000,2023-01-22 10:49:30.000,Журавлев,Денис,Мужской,Фонтанный квартал,2,Фондю,48.43,1,Анастасия Морозова,велосипед
1,2174,2023-01-30 15:20:17.000,2023-01-30 17:09:17.000,Ершова,Ольга,Женский,Радужная степь,0,Пад тай,19.10,3,Анастасия Морозова,велосипед
2,2076,2023-02-24 03:48:17.000,2023-02-24 04:42:17.000,Суханов,Артем,Мужской,Радужная степь,3,Кимчи,39.88,1,Павел Семенов,автомобиль
3,2337,2023-01-18 21:46:55.000,2023-01-18 23:02:55.000,Веселов,Валерий,Мужской,Радужная степь,0,Муссака,32.99,2,Иван Лебедев,автомобиль
4,1140,2023-02-02 17:20:33.000,2023-02-02 18:13:33.000,Калинина,Ирина,Женский,Эмпайровское кольцо,2,Тапас,29.16,2,Иван Лебедев,автомобиль


### Задание 2.6

Из полученного датасета составьте два новых:

- Первый датасет назовите `df_orders`. Поместите в него столбцы: `'order_id'`, `'time_order'`, `'last_name'`,  `'var_product'`, `'price'` и `'quantity'`.
- Второй датасет назовите `df_delivery` и оставьте в нём столбцы: `'order_id'`, `'time_delivery'`, `'district'`, `'deliveryman'`, `'transport'`.

In [20]:
#прекод
df_orders = df_proj.loc[:, ['order_id', 'time_order', 'last_name', 'var_product', 'price', 'quantity']]

df_delivery = df_proj.loc[:, ['order_id', 'time_delivery', 'district', 'deliveryman', 'transport']]


### Задание 2.7

Из датасета `df_orders` отобразите только те строки, где покупатели заказывали `'Фондю'` и в заказе было больше одного блюда.

In [21]:
#прекод
df_orders = df_orders[(df_orders['var_product'] == 'Фондю') & (df_orders['quantity'] > 1)]
df_orders

,order_id,time_order,last_name,var_product,price,quantity
233,382,2023-01-06 08:13:20.000,Боброва,Фондю,48.43,2
236,1791,2023-02-28 09:53:36.000,Журавлева,Фондю,48.43,2
257,2234,2023-02-01 08:26:01.000,Анисимова,Фондю,48.43,3
283,1552,2023-01-21 09:08:16.000,Максимов,Фондю,48.43,3
353,2187,2023-01-14 08:57:27.000,Ефимов,Фондю,48.43,3
375,1683,2023-02-01 07:02:02.000,Казаков,Фондю,48.43,2
424,262,2023-01-25 03:29:19.000,Козлова,Фондю,48.43,3
552,1127,2023-02-27 17:27:28.000,Сидорова,Фондю,48.43,3
565,1359,2023-01-15 14:06:24.000,Федорова,Фондю,48.43,2
570,882,2023-01-13 11:38:20.000,Щербаков,Фондю,48.43,2
584,825,2023-02-28 17:09:17.000,Сидоров,Фондю,48.43,3
628,898,2023-02-17 20:34:35.000,Тимофеев,Фондю,48.43,2
677,2328,2023-02-28 10:17:23.000,Фролова,Фондю,48.43,3
727,887,2023-01-09 07:12:06.000,Коновалов,Фондю,48.43,3
797,1043,2023-01-09 00:33:10.000,Ильина,Фондю,48.43,2
811,274,2023-02-15 17:35:24.000,Куликова,Фондю,48.43,3
873,890,2023-02-15 07:38:25.000,Богданов,Фондю,48.43,2
892,1775,2023-02-10 16:40:58.000,Ковалев,Фондю,48.43,2
936,1254,2023-02-11 21:14:25.000,Новиков,Фондю,48.43,3
944,873,2023-01-31 05:46:20.000,Веселова,Фондю,48.43,2
953,1768,2023-01-13 08:15:01.000,Антонова,Фондю,48.43,3
981,343,2023-01-02 01:58:52.000,Денисова,Фондю,48.43,3
1002,225,2023-02-09 19:59:33.000,Давыдова,Фондю,48.43,2
1042,1971,2023-01-14 00:45:18.000,Виноградова,Фондю,48.43,2
1099,480,2023-01-25 06:48:35.000,Цветкова,Фондю,48.43,3
1172,916,2023-02-09 11:03:48.000,Андреев,Фондю,48.43,3
1223,1760,2023-02-26 23:17:39.000,Петухова,Фондю,48.43,2
1256,2316,2023-02-27 05:41:50.000,Антонов,Фондю,48.43,2
1303,1983,2023-02-06 06:10:37.000,Соловьев,Фондю,48.43,3
1354,220,2023-02-03 12:06:21.000,Герасимова,Фондю,48.43,2
1368,892,2023-01-18 19:06:30.000,Ефимов,Фондю,48.43,2
1383,278,2023-02-12 22:44:29.000,Андреева,Фондю,48.43,3
1398,1933,2023-01-05 15:46:34.000,Матвеев,Фондю,48.43,2
1417,373,2023-01-23 16:27:56.000,Дорофеев,Фондю,48.43,3
1511,1105,2023-02-07 16:40:51.000,Филиппов,Фондю,48.43,2
1534,862,2023-01-19 02:32:25.000,Колесникова,Фондю,48.43,3
1578,1732,2023-01-11 19:25:06.000,Антонова,Фондю,48.43,3
1582,1510,2023-01-23 22:35:35.000,Анисимов,Фондю,48.43,3
1601,1109,2023-01-21 11:45:30.000,Киселев,Фондю,48.43,2
1627,642,2023-02-23 16:46:25.000,Богданов,Фондю,48.43,2
1772,2156,2023-01-16 05:55:19.000,Казакова,Фондю,48.43,2
1829,1848,2023-02-06 10:19:06.000,Федоров,Фондю,48.43,2
2057,482,2023-02-24 14:46:41.000,Мельников,Фондю,48.43,2
2196,87,2023-01-03 18:29:41.000,Большаков,Фондю,48.43,2
2300,1293,2023-02-06 19:26:51.000,Морозова,Фондю,48.43,2
2332,110,2023-02-07 03:46:21.000,Григорьева,Фондю,48.43,3
2442,473,2023-02-27 02:57:45.000,Яковлева,Фондю,48.43,3
2460,2360,2023-01-24 06:50:47.000,Большакова,Фондю,48.43,3
2604,285,2023-01-21 06:29:11.000,Тимофеев,Фондю,48.43,3
2613,1352,2023-02-09 13:27:02.000,Сидоров,Фондю,48.43,3


### Задание 2.8

Из датасета `df_delivery` отобразите столбцы `order_id` и `deliveryman`, но только те заказы, которые курьеры доставляли в район `'Эмпайровское кольцо'` на транспорте `'мотоцикл'` или в район `'Искровое ущелье'` любым другим транспортом.

In [22]:
#прекод

df_delivery_two_columns = df_delivery.query('district == "Эмпайровское кольцо" and transport == "мотоцикл" or district == "Искровое ущелье"').loc[:, ['order_id', 'deliveryman']]

df_delivery_two_columns.head()

    order_id       deliveryman
25      1863  Алексей Богданов
26      1863  Алексей Богданов
29      1162  Александр Иванов
30      1162  Алексей Богданов
34       605    Михаил Смирнов


### Задание 2.9

В основном датасете `df_proj` замените значения `'Фондю'` на `'Омлет'`, и значение `discount` на `0`, где количество блюд в заказе не превышало одного.

In [23]:
#прекод
df_proj = df_proj.replace('Фондю', 'Омлет')
df_proj.loc[df_proj['quantity'] <= 1, 'discount'] = 0
df_proj

,order_id,time_order,time_delivery,last_name,first_name,gender,district,discount,var_product,price,quantity,deliveryman,transport
0,224,2023-01-22 10:31:30.000,2023-01-22 10:49:30.000,Журавлев,Денис,Мужской,Фонтанный квартал,0,Омлет,48.43,1,Анастасия Морозова,велосипед
1,2174,2023-01-30 15:20:17.000,2023-01-30 17:09:17.000,Ершова,Ольга,Женский,Радужная степь,0,Пад тай,19.10,3,Анастасия Морозова,велосипед
2,2076,2023-02-24 03:48:17.000,2023-02-24 04:42:17.000,Суханов,Артем,Мужской,Радужная степь,0,Кимчи,39.88,1,Павел Семенов,автомобиль
3,2337,2023-01-18 21:46:55.000,2023-01-18 23:02:55.000,Веселов,Валерий,Мужской,Радужная степь,0,Муссака,32.99,2,Иван Лебедев,автомобиль
4,1140,2023-02-02 17:20:33.000,2023-02-02 18:13:33.000,Калинина,Ирина,Женский,Эмпайровское кольцо,2,Тапас,29.16,2,Иван Лебедев,автомобиль
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2643,2095,2023-02-05 05:32:11.000,2023-02-05 06:00:11.000,Смирнов,Егор,Мужской,Эмпайровское кольцо,0,Лазанья,26.54,3,Дмитрий Васильев,автомобиль
2644,1917,2023-01-07 08:41:57.000,2023-01-07 10:32:57.000,Киселева,Елена,Женский,Фонтанный квартал,4,Греческий салат,23.34,2,Дмитрий Васильев,автомобиль
2645,296,2023-02-16 05:38:44.000,2023-02-16 06:26:44.000,Матвеева,Маргарита,Женский,Эмпайровское кольцо,2,Салат Оливье,28.21,3,Ольга Кузнецова,велосипед
2646,982,2023-01-04 00:27:17.000,2023-01-04 02:16:17.000,Белоусов,Максим,Мужской,Аквамариновый берег,3,Салат Капрезе,34.39,2,Андрей Николаев,велосипед
2647,2284,2023-02-25 03:51:36.000,2023-02-25 05:17:36.000,Фомин,Алексей,Мужской,Кристальный город,0,Шашлык,39.88,1,Анастасия Морозова,велосипед